from __future__ import annotations

import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

class ContractDocsAlignmentTests(unittest.TestCase):
    def test_documentation_ia_standards_baseline_exists(self) -> None:
        docs_root = REPO_ROOT / "docs"
        standards = docs_root / "standards"
        self.assertTrue((standards / "documentation_style_guide.md").is_file())
        self.assertTrue((standards / "agent_yaml_schema.md").is_file())
        self.assertTrue((standards / "agent_task_template_examples.md").is_file())
        self.assertTrue((standards / "portal_shell_refactor_guardrails.md").is_file())
        self.assertTrue((docs_root / "plans" / "documentation_ia_remediation_backlog.md").is_file())
        self.assertTrue((docs_root / "audits" / "reports" / "documentation_ia_audit_report_2026-04-20.md").is_file())

        plan_text = (docs_root / "audits" / "archive" / "documentation_agent_yaml_optimization_plan_2026-04-16.md").read_text(
            encoding="utf-8"
        )
        self.assertIn("## Canonical Contract Links", plan_text)
        self.assertIn("docs/contracts/portal_shell_contract.md", plan_text)
        self.assertIn("docs/contracts/route_model.md", plan_text)
        self.assertIn("docs/contracts/surface_catalog.md", plan_text)
        self.assertIn("docs/contracts/portal_vocabulary_glossary.md", plan_text)

    def test_tool_operating_contract_and_stabilization_matrix_docs_exist_and_are_linked(self) -> None:
        contracts_readme = (REPO_ROOT / "docs" / "contracts" / "README.md").read_text(encoding="utf-8")
        docs_readme = (REPO_ROOT / "docs" / "README.md").read_text(encoding="utf-8")
        plans_readme = (REPO_ROOT / "docs" / "plans" / "README.md").read_text(encoding="utf-8")
        shell_contract = (REPO_ROOT / "docs" / "contracts" / "portal_shell_contract.md").read_text(encoding="utf-8")
        operating_contract = (REPO_ROOT / "docs" / "contracts" / "tool_operating_contract.md").read_text(encoding="utf-8")
        stabilization_plan = (REPO_ROOT / "docs" / "plans" / "one_shell_portal_refactor.md").read_text(encoding="utf-8")
        matrix_plan = (REPO_ROOT / "docs" / "plans" / "one_shell_stabilization_matrix.md").read_text(encoding="utf-8")
        guardrails = (REPO_ROOT / "docs" / "standards" / "portal_shell_refactor_guardrails.md").read_text(encoding="utf-8")

        self.assertIn("tool_operating_contract.md", contracts_readme)
        self.assertIn("tool_operating_contract.md", docs_readme)
        self.assertIn("one_shell_portal_refactor.md", plans_readme)
        self.assertIn("tool_operating_contract.md", shell_contract)
        self.assertIn("reflective_workspace", operating_contract)
        self.assertIn("directive_panel", operating_contract)
        self.assertIn("presentation_surface", operating_contract)
        self.assertIn("Wave 0", stabilization_plan)
        self.assertIn("Contract Matrix (Must Pass)", stabilization_plan)
        self.assertIn("/portal/system/tools/workbench-ui", matrix_plan)
        self.assertIn("test_portal_shell_stabilization_matrix", matrix_plan)
        self.assertIn("Blocking Rules", guardrails)
        self.assertIn("build_shell_composition_payload()", guardrails)

    def test_performance_benchmark_baseline_artifacts_exist(self) -> None:
        repo_root = REPO_ROOT
        self.assertTrue((repo_root / "scripts" / "benchmarks" / "build_weight.sh").is_file())
        self.assertTrue((repo_root / "scripts" / "benchmarks" / "runtime_interactions.sh").is_file())
        self.assertTrue((repo_root / "scripts" / "benchmarks" / "projection_serialization.py").is_file())

        self.assertTrue((repo_root / "benchmarks" / "data" / "portal_shell_fixture_v1.json").is_file())
        self.assertTrue((repo_root / "benchmarks" / "data" / "cts_gis_projection_fixture_v1.json").is_file())
        self.assertTrue((repo_root / "benchmarks" / "data" / "interaction_journeys_v1.json").is_file())
        self.assertTrue((repo_root / "benchmarks" / "data" / "CHECKSUMS.sha256").is_file())

        self.assertTrue((repo_root / "benchmarks" / "results" / "build_weight_baseline.json").is_file())
        self.assertTrue((repo_root / "benchmarks" / "results" / "runtime_interactions_baseline.json").is_file())
        self.assertTrue((repo_root / "benchmarks" / "results" / "projection_serialization_baseline.json").is_file())

    def test_contract_docs_use_one_shell_routes(self) -> None:
        route_model = (REPO_ROOT / "docs" / "contracts" / "route_model.md").read_text(encoding="utf-8")
        self.assertIn("/portal/api/v2/shell", route_model)
        self.assertIn("/portal/system/tools/<tool_slug>", route_model)
        self.assertIn("/portal/system/tools/workbench-ui", route_model)
        self.assertIn("/portal/api/v2/system/tools/workbench-ui", route_model)
        self.assertIn("/portal/api/v2/system/tools/aws-csm", route_model)
        self.assertIn("/portal/api/v2/system/tools/cts-gis/actions", route_model)
        self.assertIn("/portal/system", route_model)
        self.assertNotIn("/portal/system/activity", route_model)
        self.assertNotIn("/portal/system/profile-basics", route_model)
        self.assertNotIn("POST /portal/api/v2/system/tools/aws\n", route_model)
        self.assertNotIn("/portal/api/v2/system/tools/aws-narrow-write", route_model)
        self.assertNotIn("/portal/api/v2/system/tools/aws-csm-sandbox", route_model)
        self.assertNotIn("/portal/api/v2/system/tools/aws-csm-onboarding", route_model)
        self.assertNotIn("/portal/api/v2/" + "tenant", route_model)
        self.assertNotIn("/portal/api/v2/" + "admin" + "/shell", route_model)

    def test_shell_contract_and_plan_docs_describe_completed_family_unification(self) -> None:
        tool_operating_contract = (REPO_ROOT / "docs" / "contracts" / "tool_operating_contract.md").read_text(
            encoding="utf-8"
        )
        plans_readme = (REPO_ROOT / "docs" / "plans" / "README.md").read_text(encoding="utf-8")
        matrix_plan = (REPO_ROOT / "docs" / "plans" / "one_shell_stabilization_matrix.md").read_text(encoding="utf-8")
        plan_index = (
            REPO_ROOT / "docs" / "plans" / "portal_shell_unification_plan_index_2026-04-23.md"
        ).read_text(encoding="utf-8")
        execution_plan = (
            REPO_ROOT / "docs" / "plans" / "portal_shell_unification_execution_plan_2026-04-23.md"
        ).read_text(encoding="utf-8")
        renderer_plan = (
            REPO_ROOT / "docs" / "plans" / "portal_shell_region_family_renderer_migration_2026-04-23.md"
        ).read_text(encoding="utf-8")
        runtime_plan = (
            REPO_ROOT / "docs" / "plans" / "portal_shell_runtime_bundle_unification_2026-04-23.md"
        ).read_text(encoding="utf-8")
        boundary_map = (
            REPO_ROOT / "docs" / "plans" / "portal_shell_boundary_map_and_system_workbench_split_2026-04-23.md"
        ).read_text(encoding="utf-8")

        for text in (
            tool_operating_contract,
            matrix_plan,
            execution_plan,
            renderer_plan,
            boundary_map,
        ):
            self.assertIn("directive_panel", text)
            self.assertIn("reflective_workspace", text)
            self.assertIn("presentation_surface", text)

        self.assertIn("family-only shell", plans_readme)
        self.assertIn("closeout", plan_index.lower())
        self.assertIn("execution closeout record", execution_plan.lower())
        self.assertIn("renderer-side closeout record", renderer_plan.lower())
        self.assertIn("server-side closeout record", runtime_plan.lower())
        self.assertIn("shell unification is complete", boundary_map.lower())
        self.assertNotIn("legacy renderer kinds and compatibility fields are still present", execution_plan)
        self.assertNotIn("temporary CTS-GIS directive-panel compatibility path", boundary_map)
        self.assertNotIn("legacy extra bundle keys may remain", runtime_plan)

    def test_cts_gis_admin_entity_yaml_guidelines_are_published(self) -> None:
        contracts_readme = (REPO_ROOT / "docs" / "contracts" / "README.md").read_text(encoding="utf-8")
        yaml_guidelines = (
            REPO_ROOT / "docs" / "contracts" / "cts_gis_admin_entity_yaml_guidelines.md"
        ).read_text(encoding="utf-8")

        self.assertIn("cts_gis_admin_entity_yaml_guidelines.md", contracts_readme)
        self.assertIn("schema: mycite.v2.cts_gis.stage_insert.v1", yaml_guidelines)
        self.assertIn("document_id:", yaml_guidelines)
        self.assertIn("document_name:", yaml_guidelines)
        self.assertIn("operation: insert_datums", yaml_guidelines)
        self.assertIn("datums:", yaml_guidelines)
        self.assertIn("family: administrative_street", yaml_guidelines)
        self.assertIn("valueGroup: 2", yaml_guidelines)
        self.assertIn("targetNodeAddress:", yaml_guidelines)
        self.assertIn("type: msn-samras", yaml_guidelines)
        self.assertIn("type: title", yaml_guidelines)
        self.assertIn("grouped by city", yaml_guidelines)
        self.assertIn("placeholder ASCII title", yaml_guidelines)
        self.assertIn("Upload the YAML into the CTS-GIS tool", yaml_guidelines)
        self.assertIn("convert the same structure to JSON", yaml_guidelines)
        self.assertIn("Do not edit the database-backed administrative file through ad-hoc UI changes", yaml_guidelines)

    def test_contract_docs_describe_behavioral_shell_model(self) -> None:
        shell_contract = (REPO_ROOT / "docs" / "contracts" / "portal_shell_contract.md").read_text(encoding="utf-8")
        self.assertIn("ordered focus stack", shell_contract.lower())
        self.assertIn("anthology", shell_contract)
        self.assertIn("datum-file workbench", shell_contract)
        self.assertIn("system-log workbench", shell_contract)
        self.assertIn("system_log.json", shell_contract)
        self.assertIn("layered datum table", shell_contract)
        self.assertIn("activity` and `profile_basics` are workspace file modes", shell_contract)
        self.assertIn("not a tool and not a sandbox", shell_contract)
        self.assertIn("back_out", shell_contract)
        self.assertIn("current context", shell_contract.lower())
        self.assertIn("below the current focus", shell_contract.lower())
        self.assertIn("interface-panel-led", shell_contract)
        self.assertIn("top menubar is the only shell header", shell_contract.lower())
        self.assertIn("control panel", shell_contract.lower())
        self.assertIn("interface panel", shell_contract.lower())
        self.assertIn("ide-shell", shell_contract)
        self.assertIn("ide-menubar", shell_contract)
        self.assertIn("ide-body", shell_contract)
        self.assertIn("activity bar", shell_contract.lower())
        self.assertIn("workbench", shell_contract.lower())
        self.assertIn("shell asset manifest", shell_contract.lower())
        self.assertIn("selected-record focus", shell_contract.lower())
        self.assertIn("section-led", shell_contract.lower())
        self.assertIn("AWS-CSM", shell_contract)
        self.assertIn("Workbench UI", shell_contract)
        self.assertIn("CTS-GIS", shell_contract)
        self.assertIn("tool_state", shell_contract)
        self.assertIn("nimm_directive", shell_contract)
        self.assertIn("Diktataograph", shell_contract)
        self.assertIn("Garland", shell_contract)
        self.assertIn("navigation_canvas", shell_contract)
        self.assertIn("garland_split_projection", shell_contract)
        self.assertIn("geospatial_projection", shell_contract)
        self.assertIn("profile_projection", shell_contract)
        self.assertIn("directory_dropdowns", shell_contract)
        self.assertIn("samras_magnitude", shell_contract)
        self.assertIn("decode_state", shell_contract)
        self.assertIn("dropdowns", shell_contract)
        self.assertIn("active_path", shell_contract)
        self.assertIn("tabs", shell_contract)
        self.assertIn("default_tab_id", shell_contract)
        self.assertIn("fail-closed", shell_contract.lower())
        self.assertIn("blank", shell_contract.lower())
        self.assertIn("cts-gis", shell_contract.lower())
        self.assertIn("authenticated peripheral package", shell_contract.lower())
        self.assertIn("interface_panel_collapsed", shell_contract)
        self.assertIn("workbench_collapsed", shell_contract)
        self.assertIn("regions.interface_panel", shell_contract)
        self.assertIn("compatibility alias", shell_contract.lower())
        self.assertNotIn("CTS-GIS Context", shell_contract)
        self.assertNotIn("staged_diktataograph", shell_contract)
        self.assertNotIn("staged_blocks", shell_contract)
        self.assertNotIn("legacy_branch_canvas", shell_contract)
        self.assertNotIn("inspector lens", shell_contract.lower())
        self.assertNotIn("stacked focus panel", shell_contract.lower())
        self.assertNotIn("trusted" + "_tenant", shell_contract)
        self.assertNotIn("admin" + " shell", shell_contract.lower())

    def test_surface_catalog_and_routes_describe_network_as_single_workbench(self) -> None:
        route_model = (REPO_ROOT / "docs" / "contracts" / "route_model.md").read_text(encoding="utf-8")
        surface_catalog = (REPO_ROOT / "docs" / "contracts" / "surface_catalog.md").read_text(encoding="utf-8")
        readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")

        self.assertIn("/portal/network", route_model)
        self.assertIn("system_log.json", route_model)
        self.assertIn("view", route_model)
        self.assertIn("contract", route_model)
        self.assertIn("type", route_model)
        self.assertIn("record", route_model)
        self.assertNotIn("/portal/network/messages", route_model.lower())
        self.assertNotIn("/portal/network/hosted", route_model.lower())
        self.assertNotIn("/portal/network/profile", route_model.lower())
        self.assertNotIn("/portal/network/contracts", route_model.lower())

        self.assertIn("portal-instance system-log workbench", surface_catalog)
        self.assertIn("not a tool and not a sandbox", surface_catalog)
        self.assertIn("Contract correspondence", surface_catalog)
        self.assertIn("no canonical Messages/Hosted/Profile/Contracts peer-tab model", surface_catalog)
        self.assertIn("section-led", surface_catalog.lower())
        self.assertIn("control panel", surface_catalog.lower())
        self.assertIn("collapsed by default", surface_catalog.lower())
        self.assertIn("detail view", surface_catalog.lower())
        self.assertNotIn("read-only inspector", surface_catalog.lower())

        self.assertIn("portal-instance system-log workbench", readme)
        self.assertIn("system_log.json", readme)
        self.assertIn("activity bar", readme.lower())
        self.assertIn("interface panel", readme.lower())

    def test_surface_catalog_describes_one_aws_csm_tool(self) -> None:
        route_model = (REPO_ROOT / "docs" / "contracts" / "route_model.md").read_text(encoding="utf-8")
        surface_catalog = (REPO_ROOT / "docs" / "contracts" / "surface_catalog.md").read_text(encoding="utf-8")
        docs_readme = (REPO_ROOT / "docs" / "README.md").read_text(encoding="utf-8")

        self.assertIn("system.tools.aws_csm", surface_catalog)
        self.assertIn("system.tools.workbench_ui", surface_catalog)
        self.assertNotIn("system.tools.aws_narrow_write", surface_catalog)
        self.assertNotIn("system.tools.aws_csm_sandbox", surface_catalog)
        self.assertNotIn("system.tools.aws_csm_onboarding", surface_catalog)
        self.assertIn("/portal/system/tools/aws-csm", route_model)
        self.assertNotIn("/portal/system/tools/aws-narrow-write", route_model)
        self.assertNotIn("/portal/system/tools/aws-csm-sandbox", route_model)
        self.assertNotIn("/portal/system/tools/aws-csm-onboarding", route_model)
        self.assertIn("/portal/system/tools/aws-csm", docs_readme)
        self.assertIn("/portal/system/tools/workbench-ui", docs_readme)
        self.assertIn("interface-panel-led", surface_catalog)
        self.assertIn("workbench-primary", surface_catalog)
        self.assertIn("hidden by default", surface_catalog)
        self.assertIn("secondary workbench content", surface_catalog.lower())
        self.assertIn("directive_panel", surface_catalog)
        self.assertIn("reflective_workspace", surface_catalog)
        self.assertIn("presentation_surface", surface_catalog)
        self.assertIn("system.tools.cts_gis", surface_catalog)
        self.assertIn("/portal/system/tools/cts-gis", route_model)
        self.assertIn("Diktataograph", surface_catalog)
        self.assertIn("Garland", surface_catalog)
        self.assertIn("navigation_canvas", surface_catalog)
        self.assertIn("garland_split_projection", surface_catalog)
        self.assertIn("tabs", surface_catalog)
        self.assertIn("default_tab_id", surface_catalog)
        self.assertIn("geospatial_projection", surface_catalog)
        self.assertIn("profile_projection", surface_catalog)
        self.assertIn("directory_dropdowns", surface_catalog)
        self.assertIn("samras_magnitude", surface_catalog)
        self.assertIn("decode_state", surface_catalog)
        self.assertNotIn("CTS-GIS Context", surface_catalog)
        self.assertNotIn("staged_blocks", surface_catalog)
        self.assertIn("tool-local state is body-carried", surface_catalog.lower())

    def test_fnd_dcm_docs_describe_manifest_surface_and_shared_conventions(self) -> None:
        route_model = (REPO_ROOT / "docs" / "contracts" / "route_model.md").read_text(encoding="utf-8")
        surface_catalog = (REPO_ROOT / "docs" / "contracts" / "surface_catalog.md").read_text(encoding="utf-8")
        shell_contract = (REPO_ROOT / "docs" / "contracts" / "portal_shell_contract.md").read_text(encoding="utf-8")
        tool_contract = (REPO_ROOT / "docs" / "contracts" / "fnd_dcm_tool_contract.md").read_text(encoding="utf-8")
        manifest_conventions = (REPO_ROOT / "docs" / "contracts" / "fnd_dcm_manifest_conventions.md").read_text(encoding="utf-8")
        docs_readme = (REPO_ROOT / "docs" / "README.md").read_text(encoding="utf-8")
        contracts_readme = (REPO_ROOT / "docs" / "contracts" / "README.md").read_text(encoding="utf-8")
        root_readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")

        self.assertIn("/portal/system/tools/fnd-dcm", route_model)
        self.assertIn("/portal/api/v2/system/tools/fnd-dcm", route_model)
        self.assertIn("site", route_model)
        self.assertIn("collection", route_model)
        self.assertIn("system.tools.fnd_dcm", surface_catalog)
        self.assertIn("interface-panel-led", surface_catalog)
        self.assertIn("hidden by default", surface_catalog)
        self.assertIn("runtime-owned", shell_contract)
        self.assertIn("hosted-manifest control surface", shell_contract)
        self.assertIn("mycite.v2.portal.system.tools.fnd_dcm.request.v1", tool_contract)
        self.assertIn("hosted_site_manifest_visibility", tool_contract)
        self.assertIn("extensions", manifest_conventions)
        self.assertIn("summary_bio", manifest_conventions)
        self.assertIn("socials", manifest_conventions)
        self.assertIn("fnd_dcm_tool_contract.md", contracts_readme)
        self.assertIn("/portal/system/tools/fnd-dcm", docs_readme)
        self.assertIn("/portal/system/tools/fnd-dcm", root_readme)

    def test_route_model_uses_detail_lens_and_interface_panel_terms(self) -> None:
        route_model = (REPO_ROOT / "docs" / "contracts" / "route_model.md").read_text(encoding="utf-8")
        self.assertIn("detail lens", route_model.lower())
        self.assertIn("Interface Panel detail view", route_model)
        self.assertNotIn("inspector lens", route_model.lower())
        self.assertIn("tool_state", route_model)
        self.assertIn("nimm_directive", route_model)
        self.assertIn("Diktataograph", route_model)
        self.assertIn("Garland", route_model)
        self.assertIn("navigation_canvas", route_model)
        self.assertIn("garland_split_projection", route_model)
        self.assertIn("tabs", route_model)
        self.assertIn("default_tab_id", route_model)
        self.assertIn("directory_dropdowns", route_model)
        self.assertIn("samras_magnitude", route_model)
        self.assertIn("decode_state", route_model)
        self.assertIn("active_path", route_model)
        self.assertNotIn("CTS-GIS Context", route_model)
        self.assertNotIn("staged_diktataograph", route_model)
        self.assertNotIn("staged_blocks", route_model)
        self.assertNotIn("legacy_branch_canvas", route_model)

    def test_workbench_ui_contract_docs_describe_two_pane_sql_sheet(self) -> None:
        route_model = (REPO_ROOT / "docs" / "contracts" / "route_model.md").read_text(encoding="utf-8")
        surface_catalog = (REPO_ROOT / "docs" / "contracts" / "surface_catalog.md").read_text(encoding="utf-8")
        shell_contract = (REPO_ROOT / "docs" / "contracts" / "portal_shell_contract.md").read_text(encoding="utf-8")
        docs_readme = (REPO_ROOT / "docs" / "README.md").read_text(encoding="utf-8")
        root_readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")

        self.assertIn("document_filter", route_model)
        self.assertIn("document_sort", route_model)
        self.assertIn("document_dir", route_model)
        self.assertIn("group", route_model)
        self.assertIn("workbench_lens", route_model)
        self.assertIn("source", route_model)
        self.assertIn("prefers the first available `sandbox:cts_gis:*` document", route_model)
        self.assertIn("version_hash", route_model)
        self.assertIn("hyphae_hash", route_model)
        self.assertIn("authority inspector", surface_catalog)
        self.assertIn("two-pane", surface_catalog)
        self.assertIn("document table", surface_catalog.lower())
        self.assertIn("does not replace the reducer-owned `/portal/system` anthology workspace", surface_catalog)
        self.assertIn("version_hash", surface_catalog)
        self.assertIn("hyphae_hash", surface_catalog)
        self.assertIn("Grouping", shell_contract)
        self.assertIn("Lens", shell_contract)
        self.assertIn("Source", shell_contract)
        self.assertIn("does not replace the reducer-owned `SYSTEM` anthology workspace", shell_contract)
        self.assertIn("sticky-header", shell_contract)
        self.assertIn("selected-row", shell_contract)
        self.assertIn("version_hash", shell_contract)
        self.assertIn("authority inspector", docs_readme)
        self.assertIn("does not replace `/portal/system`", root_readme)
        self.assertIn("two-pane", docs_readme)
        self.assertIn("two-pane", root_readme)

    def test_cts_gis_contract_docs_capture_selection_aligned_garland_behavior(self) -> None:
        shell_contract = (REPO_ROOT / "docs" / "contracts" / "portal_shell_contract.md").read_text(encoding="utf-8")
        route_model = (REPO_ROOT / "docs" / "contracts" / "route_model.md").read_text(encoding="utf-8")
        surface_catalog = (REPO_ROOT / "docs" / "contracts" / "surface_catalog.md").read_text(encoding="utf-8")
        samras_addressing = (REPO_ROOT / "docs" / "contracts" / "cts_gis_samras_addressing.md").read_text(encoding="utf-8")
        contracts_readme = (REPO_ROOT / "docs" / "contracts" / "README.md").read_text(encoding="utf-8")
        docs_readme = (REPO_ROOT / "docs" / "README.md").read_text(encoding="utf-8")

        self.assertIn("normalizes `tool_state.aitas.intention_rule_id` to `self`", shell_contract)
        self.assertIn("blank current-profile state", shell_contract)
        self.assertIn("selection normalization", route_model.lower())
        self.assertIn("normalizes intention to `self`", route_model)
        self.assertIn("blank but stateful `profile_projection`", route_model)
        self.assertIn("Garland remains visible and stateful", surface_catalog)
        self.assertIn("normalizes `Intention` to `self`", surface_catalog)
        self.assertIn("Selection Normalization", samras_addressing)
        self.assertIn("Garland Coupling", samras_addressing)
        self.assertIn("node-specific profile source document", samras_addressing)
        self.assertIn("tool_mediation_surface_archetype.md", contracts_readme)
        self.assertIn("tool_mediation_surface_archetype.md", docs_readme)
        self.assertIn("cts_gis_compiled_artifact_contract.md", contracts_readme)
        self.assertIn("cts_gis_operating_contract.md", contracts_readme)
        self.assertIn("cts_gis_legacy_alias_retirement_timeline.md", contracts_readme)


if __name__ == "__main__":
    unittest.main()
