from __future__ import annotations

import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


class ContractDocsAlignmentTests(unittest.TestCase):
    def test_contract_docs_use_one_shell_routes(self) -> None:
        route_model = (REPO_ROOT / "docs" / "contracts" / "route_model.md").read_text(encoding="utf-8")
        self.assertIn("/portal/api/v2/shell", route_model)
        self.assertIn("/portal/system/tools/<tool_slug>", route_model)
        self.assertIn("/portal/api/v2/system/tools/aws-csm", route_model)
        self.assertIn("/portal/system", route_model)
        self.assertNotIn("/portal/system/activity", route_model)
        self.assertNotIn("/portal/system/profile-basics", route_model)
        self.assertNotIn("POST /portal/api/v2/system/tools/aws\n", route_model)
        self.assertNotIn("/portal/api/v2/system/tools/aws-narrow-write", route_model)
        self.assertNotIn("/portal/api/v2/system/tools/aws-csm-sandbox", route_model)
        self.assertNotIn("/portal/api/v2/system/tools/aws-csm-onboarding", route_model)
        self.assertNotIn("/portal/api/v2/" + "tenant", route_model)
        self.assertNotIn("/portal/api/v2/" + "admin" + "/shell", route_model)

    def test_contract_docs_describe_behavioral_shell_model(self) -> None:
        shell_contract = (REPO_ROOT / "docs" / "contracts" / "portal_shell_contract.md").read_text(encoding="utf-8")
        self.assertIn("ordered focus stack", shell_contract.lower())
        self.assertIn("anthology", shell_contract)
        self.assertIn("datum-file workbench", shell_contract)
        self.assertIn("system-log workbench", shell_contract)
        self.assertIn("system_log.json", shell_contract)
        self.assertIn("layered datum table", shell_contract)
        self.assertIn("activity` and `profile_basics` are workspace file modes", shell_contract)
        self.assertIn("not a tool and not a sandbox", shell_contract)
        self.assertIn("back_out", shell_contract)
        self.assertIn("current context", shell_contract.lower())
        self.assertIn("below the current focus", shell_contract.lower())
        self.assertIn("interface-panel-led", shell_contract)
        self.assertIn("top menubar is the only shell header", shell_contract.lower())
        self.assertIn("control panel", shell_contract.lower())
        self.assertIn("interface panel", shell_contract.lower())
        self.assertIn("ide-shell", shell_contract)
        self.assertIn("ide-menubar", shell_contract)
        self.assertIn("ide-body", shell_contract)
        self.assertIn("activity bar", shell_contract.lower())
        self.assertIn("workbench", shell_contract.lower())
        self.assertIn("shell asset manifest", shell_contract.lower())
        self.assertIn("selected-record focus", shell_contract.lower())
        self.assertIn("section-led", shell_contract.lower())
        self.assertIn("AWS-CSM", shell_contract)
        self.assertIn("CTS-GIS", shell_contract)
        self.assertIn("tool_state", shell_contract)
        self.assertIn("nimm_directive", shell_contract)
        self.assertIn("Diktataograph", shell_contract)
        self.assertIn("Garland", shell_contract)
        self.assertIn("navigation_canvas", shell_contract)
        self.assertIn("garland_split_projection", shell_contract)
        self.assertIn("geospatial_projection", shell_contract)
        self.assertIn("profile_projection", shell_contract)
        self.assertIn("four visible regions", shell_contract.lower())
        self.assertIn("staged_diktataograph", shell_contract)
        self.assertIn("staged_blocks", shell_contract)
        self.assertIn("legacy_branch_canvas", shell_contract)
        self.assertIn("staged_root_opening", shell_contract)
        self.assertIn("real_garland_projection", shell_contract)
        self.assertIn("real_diktataograph_projection", shell_contract)
        self.assertIn("blank", shell_contract.lower())
        self.assertIn("cts-gis", shell_contract.lower())
        self.assertIn("authenticated peripheral package", shell_contract.lower())
        self.assertIn("interface_panel_collapsed", shell_contract)
        self.assertIn("workbench_collapsed", shell_contract)
        self.assertIn("regions.interface_panel", shell_contract)
        self.assertIn("compatibility alias", shell_contract.lower())
        self.assertNotIn("inspector lens", shell_contract.lower())
        self.assertNotIn("stacked focus panel", shell_contract.lower())
        self.assertNotIn("trusted" + "_tenant", shell_contract)
        self.assertNotIn("admin" + " shell", shell_contract.lower())

    def test_surface_catalog_and_routes_describe_network_as_single_workbench(self) -> None:
        route_model = (REPO_ROOT / "docs" / "contracts" / "route_model.md").read_text(encoding="utf-8")
        surface_catalog = (REPO_ROOT / "docs" / "contracts" / "surface_catalog.md").read_text(encoding="utf-8")
        readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")

        self.assertIn("/portal/network", route_model)
        self.assertIn("system_log.json", route_model)
        self.assertIn("view", route_model)
        self.assertIn("contract", route_model)
        self.assertIn("type", route_model)
        self.assertIn("record", route_model)
        self.assertNotIn("/portal/network/messages", route_model.lower())
        self.assertNotIn("/portal/network/hosted", route_model.lower())
        self.assertNotIn("/portal/network/profile", route_model.lower())
        self.assertNotIn("/portal/network/contracts", route_model.lower())

        self.assertIn("portal-instance system-log workbench", surface_catalog)
        self.assertIn("not a tool and not a sandbox", surface_catalog)
        self.assertIn("Contract correspondence", surface_catalog)
        self.assertIn("no canonical Messages/Hosted/Profile/Contracts peer-tab model", surface_catalog)
        self.assertIn("section-led", surface_catalog.lower())
        self.assertIn("control panel", surface_catalog.lower())
        self.assertIn("collapsed by default", surface_catalog.lower())
        self.assertIn("detail view", surface_catalog.lower())
        self.assertNotIn("read-only inspector", surface_catalog.lower())

        self.assertIn("portal-instance system-log workbench", readme)
        self.assertIn("system_log.json", readme)
        self.assertIn("activity bar", readme.lower())
        self.assertIn("interface panel", readme.lower())

    def test_surface_catalog_describes_one_aws_csm_tool(self) -> None:
        route_model = (REPO_ROOT / "docs" / "contracts" / "route_model.md").read_text(encoding="utf-8")
        surface_catalog = (REPO_ROOT / "docs" / "contracts" / "surface_catalog.md").read_text(encoding="utf-8")
        docs_readme = (REPO_ROOT / "docs" / "README.md").read_text(encoding="utf-8")

        self.assertIn("system.tools.aws_csm", surface_catalog)
        self.assertNotIn("system.tools.aws_narrow_write", surface_catalog)
        self.assertNotIn("system.tools.aws_csm_sandbox", surface_catalog)
        self.assertNotIn("system.tools.aws_csm_onboarding", surface_catalog)
        self.assertIn("/portal/system/tools/aws-csm", route_model)
        self.assertNotIn("/portal/system/tools/aws-narrow-write", route_model)
        self.assertNotIn("/portal/system/tools/aws-csm-sandbox", route_model)
        self.assertNotIn("/portal/system/tools/aws-csm-onboarding", route_model)
        self.assertIn("/portal/system/tools/aws-csm", docs_readme)
        self.assertIn("interface-panel-led", surface_catalog)
        self.assertIn("hidden by default", surface_catalog)
        self.assertIn("secondary workbench content", surface_catalog.lower())
        self.assertIn("system.tools.cts_gis", surface_catalog)
        self.assertIn("/portal/system/tools/cts-gis", route_model)
        self.assertIn("Diktataograph", surface_catalog)
        self.assertIn("Garland", surface_catalog)
        self.assertIn("navigation_canvas", surface_catalog)
        self.assertIn("garland_split_projection", surface_catalog)
        self.assertIn("geospatial_projection", surface_catalog)
        self.assertIn("profile_projection", surface_catalog)
        self.assertIn("staged_blocks", surface_catalog)
        self.assertIn("tool-local state is body-carried", surface_catalog.lower())

    def test_route_model_uses_detail_lens_and_interface_panel_terms(self) -> None:
        route_model = (REPO_ROOT / "docs" / "contracts" / "route_model.md").read_text(encoding="utf-8")
        self.assertIn("detail lens", route_model.lower())
        self.assertIn("Interface Panel detail view", route_model)
        self.assertNotIn("inspector lens", route_model.lower())
        self.assertIn("tool_state", route_model)
        self.assertIn("nimm_directive", route_model)
        self.assertIn("Diktataograph", route_model)
        self.assertIn("Garland", route_model)
        self.assertIn("navigation_canvas", route_model)
        self.assertIn("garland_split_projection", route_model)
        self.assertIn("staged_diktataograph", route_model)
        self.assertIn("staged_blocks", route_model)
        self.assertIn("legacy_branch_canvas", route_model)
        self.assertIn("real_garland_projection", route_model)
        self.assertIn("real_diktataograph_projection", route_model)


if __name__ == "__main__":
    unittest.main()
