"""Minimal Hanus shell contracts and reducer for the phase-03 MVP slice."""

from .admin_shell import (
    ADMIN_BAND0_NAME,
    ADMIN_BAND1_AWS_NAME,
    ADMIN_BAND2_AWS_NAME,
    ADMIN_ENTRYPOINT_ID,
    ADMIN_EXPOSURE_INTERNAL_ONLY,
    ADMIN_EXPOSURE_TRUSTED_TENANT_NARROW_WRITE,
    ADMIN_EXPOSURE_TRUSTED_TENANT_READ_ONLY,
    ADMIN_HOME_STATUS_SLICE_ID,
    ADMIN_SHELL_ENTRY_SLICE_ID,
    ADMIN_SHELL_REQUEST_SCHEMA,
    ADMIN_SHELL_STATE_SCHEMA,
    ADMIN_TOOL_REGISTRY_SLICE_ID,
    AWS_NARROW_WRITE_ENTRYPOINT_ID,
    AWS_NARROW_WRITE_SLICE_ID,
    AWS_READ_ONLY_ENTRYPOINT_ID,
    AWS_READ_ONLY_SLICE_ID,
    AdminShellRequest,
    AdminShellSelection,
    AdminSurfaceCatalogEntry,
    AdminTenantScope,
    AdminToolLaunchDecision,
    AdminToolRegistryEntry,
    build_admin_surface_catalog,
    build_admin_tool_registry_entries,
    resolve_admin_tool_launch,
    resolve_admin_shell_request,
)
from .contracts import (
    SHELL_ACTION_SCHEMA,
    SHELL_RESULT_SCHEMA,
    SHELL_STATE_SCHEMA,
    ShellAction,
    ShellResult,
    ShellState,
)
from .reducer import reduce_shell_action

__all__ = [
    "ADMIN_BAND0_NAME",
    "ADMIN_BAND1_AWS_NAME",
    "ADMIN_BAND2_AWS_NAME",
    "ADMIN_ENTRYPOINT_ID",
    "ADMIN_EXPOSURE_INTERNAL_ONLY",
    "ADMIN_EXPOSURE_TRUSTED_TENANT_NARROW_WRITE",
    "ADMIN_EXPOSURE_TRUSTED_TENANT_READ_ONLY",
    "ADMIN_HOME_STATUS_SLICE_ID",
    "ADMIN_SHELL_ENTRY_SLICE_ID",
    "ADMIN_SHELL_REQUEST_SCHEMA",
    "ADMIN_SHELL_STATE_SCHEMA",
    "ADMIN_TOOL_REGISTRY_SLICE_ID",
    "AWS_NARROW_WRITE_ENTRYPOINT_ID",
    "AWS_NARROW_WRITE_SLICE_ID",
    "AWS_READ_ONLY_ENTRYPOINT_ID",
    "AWS_READ_ONLY_SLICE_ID",
    "AdminShellRequest",
    "AdminShellSelection",
    "AdminSurfaceCatalogEntry",
    "AdminTenantScope",
    "AdminToolLaunchDecision",
    "AdminToolRegistryEntry",
    "SHELL_ACTION_SCHEMA",
    "SHELL_RESULT_SCHEMA",
    "SHELL_STATE_SCHEMA",
    "ShellAction",
    "ShellResult",
    "ShellState",
    "build_admin_surface_catalog",
    "build_admin_tool_registry_entries",
    "reduce_shell_action",
    "resolve_admin_tool_launch",
    "resolve_admin_shell_request",
]
